### ISSUE TITLE
请慎用apt upgrade & yum update -y

### ISSUE THREAD

**Issue by wsa01378** [hijkpw/scripts#13]
有时候系统已经稳定态大半年，试一下你的脚本结果给我apt upgrade  -y 自动刷进去百多个新插件。
真后悔没检查你脚本是否包含apt upgrade  -y
黑客大会你看过就知道，0day只从新版本组件入手

**Comment by hijkpw** [comment]
感谢反馈，我会考虑删除更新系统的代码

**Comment by hijkpw** [comment]
已禁用更新系统功能
