### ISSUE TITLE
CentOS 6

### ISSUE THREAD

**Issue by slrslr** [hijkpw/scripts#16]
Please how to install v2ray on Cent0S 6?

> wget https://raw.githubusercontent.com/hijkpw/scripts/master/centos_install_v2ray.sh -O -|bash
> 系统版本:  CentOS release 6.10 (Final)
>  不受支持的CentOS版本

translation: Unsupported CentOS version

**Comment by hijkpw** [comment]
try this: wget https://raw.githubusercontent.com/hijkpw/scripts/master/centos_install_v2ray.sh -O -| bash

**Comment by hijkpw** [comment]
sorry, the cammand is: wget [https://raw.githubusercontent.com/hijkpw/scripts/master/goV2.sh](https://raw.githubusercontent.com/hijkpw/scripts/master/centos_install_v2ray.sh) -O -| bash

**Comment by slrslr** [comment]
Thank you for help, it worked :+1::

`wget https://raw.githubusercontent.com/hijkpw/scripts/master/goV2.sh -O -|bash`

Then setup the service:
`wget https://raw.githubusercontent.com/slrslr/Miscellaneous-bash-scripts/master/etc_init.d_v2ray -O v2ray;sudo mv v2ray /etc/init.d/;sudo chmod +x /etc/init.d/v2ray;sudo chkconfig v2ray on;sudo service v2ray start`

alternative file: https://pastebin.com/raw/1tBwvaCG
