### ISSUE TITLE
能生成相应的客户端的配置文件吗？

### ISSUE THREAD

**Issue by 0x018** [hijkpw/scripts#2]
如题，服务器自动安装完成后，能自动生成对应的提供给客户端使用的配置文件吗？

**Comment by hijkpw** [comment]
会输出配置信息，但不会输出配置文件

Sent from ProtonMail Mobile

在 周一, 2月 24, 2020 在 21:27, buigMaker <notifications@github.com> 来信：

**Comment by 0x018** [comment]
碰到的问题：
1.不是ubuntu，但是安装方式和ubuntu一致，建议系统检测可以手动跳过
2.cryptography版本太低会导致失败，建议加上本版检测，自动更新升级
3.运行失败，调整脚本后，重来一遍希望可以跳过已经安装的
4.安装完成后，nginx下的  Flatfy V3.zip 是啥？？

**Comment by hijkpw** [comment]
1. 你说的是debian吗？本人没有用过，不是很清楚；
2. crypt这个确实是问题，有空我改一下
3. 目前就会跳过已安装的；
4. Flatfy是一个网站模板，目前已经移除没用了

**Comment by hijkpw** [comment]
已经添加cryptography的自动检测
