### ISSUE TITLE
Failed to copy V2Ray binary and resources.

### ISSUE THREAD

**Issue by guoapeng** [hijkpw/scripts#32]
When I install through the script centos_install_v2ray.sh, I encountered the following issue. 
I am wondering how to resolve the issue manually. could you please advice if you have any idea?

安装v2ray...
Installing V2Ray v5.3.0 on x86_64
Downloading V2Ray: https://github.com/v2fly/v2ray-core/releases/download/v5.3.0/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 11.1M  100 11.1M    0     0  21.8M      0 --:--:-- --:--:-- --:--:-- 21.8M
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /usr/bin/v2ray/geosite.dat  
  inflating: /usr/bin/v2ray/geoip.dat  
  inflating: /usr/bin/v2ray/v2ray    
caution: filename not matched:  v2ctl
Failed to copy V2Ray binary and resources.
  CentOS Linux 7 (Core) 安装V2ray失败，请到 https://hijk.art 网站反馈

**Comment by barbiekingkong** [comment]
您好，您的邮件我已经收到了，我会在第一时间给您回复的，谢谢~  鲍澎

**Comment by guoapeng** [comment]
the cause is that the file v2ctl has been removed since version 5 of v2ray. I manually resolved the issue by updating the script goV2.sh to remove v2ctl related params. and execute the goV2.sh seperately before running the one click installation script.
and skipping the goV2.sh exection in the one click installation script.

```bash
 unzip -oj "$1" "$2v2ray" "$2v2ctl" "$2geoip.dat" "$2geosite.dat" -d '/usr/bin/v2ray' && \     ## remove param "$2v2ctl" 
    chmod +x '/usr/bin/v2ray/v2ray' '/usr/bin/v2ray/v2ctl' || {                              ## remove '/usr/bin/v2ray/v2ctl' 
        colorEcho ${RED} "Failed to copy V2Ray binary and resources."
        return 1
    }
```

**Comment by barbiekingkong** [comment]
您好，您的邮件我已经收到了，我会在第一时间给您回复的，谢谢~  鲍澎
