### ISSUE TITLE
关于伪装脚本3月1日ping不通443端口的问题

### ISSUE THREAD

**Issue by 4t145** [hijkpw/scripts#4]
使用centos7, 
按照

> 今天（3月1日），用伪装脚本安装的人无法上外网，是因为之前脚本里有一个bug，解决办法如下：连接到服务器，先运行这个命令：sed -i '/certbot/d' /etc/crontab(该命令无任何输出），然后再运行一次一键脚本。

但是似乎这还不够, 提示certbot command not found
按照[certbot官网](https://certbot.eff.org/) 安装certbot后解决

**Comment by hijkpw** [comment]
重新运行一键脚本会自动安装certbot，如果无法安装上，脚本会报错退出

提示certbot command not found前面的输出是什么？

在 周日, 3月 1, 2020 在 16:36, 4t145 <notifications@github.com> 来信：

**Comment by 4t145** [comment]
> which: no certbot in  (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/node-v8.9.4-linux-x64/bin:/root/bin)
/dev/fd/63: line 185: certbot: command not found

除此之外, 之前还有一些
> Requirement already satisfied ... (from certbot)

再之前有warning
> Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.

是因为我用的root用户, 所以装了之后找不到吗

**Comment by hijkpw** [comment]
更前面一些的输出，我想看看为什么安装certbot失败

在 周日, 3月 1, 2020 在 16:54, 4t145 <notifications@github.com> 来信：

**Comment by 4t145** [comment]
> 系统版本:  CentOS Linux release 7.7.1908 (Core)
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.intergrid.com.au
 * elrepo: syd.mirror.rackspace.com
 * epel: syd.mirror.rackspace.com
 * extras: mirror.intergrid.com.au
 * updates: mirror.intergrid.com.au
Package 32:bind-utils-9.11.4-9.P2.el7.x86_64 already installed and latest version
Package curl-7.29.0-54.el7_7.2.x86_64 already installed and latest version
Nothing to do
 
 本脚本为带伪装的一键脚本，运行之前请确认如下条件已经具备：
  1. 一个域名
  2. 域名的某个主机名解析指向当前服务器ip（149.28.176.146）
 
确认满足按y，按其他退出脚本：y
请输入您的主机名：fuck.4t145.space
请输入伪装路径，以/开头：/fuckmegfw 
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
安装必要软件
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.intergrid.com.au
 * elrepo: syd.mirror.rackspace.com
 * epel: syd.mirror.rackspace.com
 * extras: mirror.intergrid.com.au
 * updates: mirror.intergrid.com.au
Package epel-release-7-12.noarch already installed and latest version
Package 1:telnet-0.17-64.el7.x86_64 already installed and latest version
Package wget-1.14-18.el7_6.1.x86_64 already installed and latest version
Package 2:vim-enhanced-7.4.629-6.el7.x86_64 already installed and latest version
Package net-tools-2.0-0.25.20131004git.el7.x86_64 already installed and latest version
Package ntpdate-4.2.6p5-29.el7.centos.x86_64 already installed and latest version
Package unzip-6.0-20.el7.x86_64 already installed and latest version
Nothing to do
BBR模块已安装
安装v2ray...
Latest version v4.22.1 is already installed.
 1 Mar 15:41:02 ntpdate[31654]: adjust time server 128.138.140.44 offset -0.011753 sec
v2ray安装成功！
Warning: ALREADY_ENABLED: http
success
Warning: ALREADY_ENABLED: https
success
success
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.intergrid.com.au
 * elrepo: syd.mirror.rackspace.com
 * epel: syd.mirror.rackspace.com
 * extras: mirror.intergrid.com.au
 * updates: mirror.intergrid.com.au
Package 1:nginx-1.16.1-1.el7.x86_64 already installed and latest version
Nothing to do

这是之前的全部信息啦

**Comment by hijkpw** [comment]
你这应该是特例，看了一下脚本和你提供的信息，certbot应该是安装上了，可能不在path路径里

**Comment by 4t145** [comment]
Ok. 谢谢你了
